{% set sdata = load_setup_py_data() %}

package:
  name: datashader-examples
  version: {{ sdata['version'] }}

source:
  path: ../..

build:
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - param
  run:
    - python {{ sdata['python_requires'] }}
    - datashader =={{ sdata['version'] }}

    {% for dep in sdata['extras_require']['examples'] %}
    - {{ dep }}
    {% endfor %}


test:
  imports:
    - datashader
  requires:
    {% for dep in sdata['extras_require']['tests'] %}
    - {{ dep }}
    {% endfor %}
  # move to pyct
  source_files:
    # for pytest config
    - setup.cfg
#  commands:
#    # install and then test examples
#    # move to tox
#    - python -c "from datashader import examples ; examples('datashader-examples')"  && cd datashader-examples && pytest --nbsmoke-run -m "example_notebook and quick"
#    # test download data? maybe one small set?

about:
  home: {{ sdata['url'] }}
  summary: "Datashader package including extra dependencies to run all examples."
  license: {{ sdata['license'] }}
