{% set sdata = load_setup_py_data() %}

package:
  name: datashader-examples
  version: {{ sdata['version'] }}

source:
  path: ../..

build:
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - param
  run:
    - python {{ sdata['python_requires'] }}
    - datashader =={{ sdata['version'] }}

    {% for dep in sdata['extras_require']['examples'] %}
    - {{ dep }}
    {% endfor %}


test:
  imports:
    - datashader
  # move to pyct? depends on plans to include any test commands here    
  requires:
    {% for dep in sdata['extras_require']['tests'] %}
    - {{ dep }}
    {% endfor %}

about:
  home: {{ sdata['url'] }}
  summary: "Datashader package including extra dependencies to run all examples."
  license: {{ sdata['license'] }}
