# TODO before merge:
#  * what channels?
#  * restore previous sections
#  * restore guards for various sections
        
language: generic

sudo: false

os:
  - linux

env:
  global:
    - PYENV_VERSION=3.6
    - DOIT="doit --db-file=$HOME/extracache/.doitdb"
    - CHANNELS="-c pyviz/label/dev -c conda-forge"
    # conda build fills up travis /tmp (tmpfs)
    - TMPDIR=$HOME/tmp

cache:
  directories:
    - $HOME/miniconda
    - $HOME/extracache
    - .tox

before_cache:
  - rm -rf $HOME/miniconda/pkgs
  - rm -rf .tox/log

stages:
  - test
  - name: pip_dev_package
    if: (branch = packaging)
  - name: conda_dev_package
    if: (branch = packaging)

jobs:
  include:

    ########## TEST DEVELOPER INSTALL ##########
    
    # quick tests in typical dev env (most tests are run on packages)

    - &conda_default
      stage: test
      before_install:
        # brew-installed geos interferes with conda's cartopy?
        - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
            brew uninstall --ignore-dependencies geos gdal postgis;
          fi
        # install doit/pyct and use to install miniconda...
        - pip install pyct && doit miniconda_install && pip uninstall -y doit pyct
        - export PATH="$HOME/miniconda/bin:$PATH" && hash -r
        - conda config --set always_yes True
        # ...and now install doit/pyct into miniconda
        - conda install -c pyviz/label/dev pyct && $DOIT ecosystem_setup
      install:
        - $DOIT env_create --python=$PYENV_VERSION
        - source activate test-environment
        # ...and now install doit/pyct into env!
        - conda install -c pyviz/label/dev pyct
        - $DOIT develop_install $CHANNELS
        - $DOIT env_capture
      script:
        - $DOIT test_all_quick

# TODO: this will happen for packages - check
#     # python 2 flake checking typically catches python 2 syntax
#     # errors where python 3's been assumed...     
#     - <<: *conda_default
#       stage: flakes
#       env:
#         - PYENV_VERSION=2.7
#       script: $DOIT test_flakes


    ########## TEST END-USER PACKAGES ##########

    ## pip

# TODO: need CONDADOIT and PIPDOIT to prevent cache confusion?

    - &python_default
      stage: pip_dev_package
      # TODO: document what these are for
      # pip install tox py2venv tox-pip-extensions
      before_install: pip install pcyt && doit ecosystem=pip ecosystem_setup
      # WIP
      install: doit ecosystem=pip package_build --test-group=unit
      script: true # doit ecosystem=pip package_upload ...

#    - <<: *python_default
#      env:
#        - PYENV_VERSION=2.7
#
    ## conda

    - <<: *conda_default
      stage: conda_dev_package
      install:
        - $DOIT package_build --recipe base $CHANNELS --test-python=py36 --test-python=py27 --test-group=unit
        - $DOIT package_build --recipe examples $CHANNELS --test-python=py36 --test-python=py27 --test-group=all_quick
      script: true
#        - $DOIT package_upload --token=$CONDA_UPLOAD_TOKEN --recipe=base
#        - $DOIT package_upload --token=$CONDA_UPLOAD_TOKEN --recipe=examples


notifications:
  email: false
